USE DATABASE YELPWEATHER;
USE SCHEMA DWH;

SELECT MIN(DATE), MAX(DATE)
FROM DWH.FACT_CLIMATE_REVIEW;

SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
FROM DWH.FACT_CLIMATE_REVIEW
GROUP BY DATE, BUSINESS_ID
LIMIT 1000;



//Finding the average temperature correlation
SELECT CORR(AVG_STARS, (T.MIN + T.MAX)/2)
FROM(
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
    FROM DWH.FACT_CLIMATE_REIVEW
    GROUP BY DATE, BUSINESS_ID
) AS R
JOIN DWH.DIM_TEMPERATURE T ON R.DATE = T.DATE
JOIN DWH.DIM_PRECIPITATION P ON R.DATE = P.DATE;



//Finding the correlation on precipitation
SELECT CORR(AVG_STARS, P.PRECIPITATION)
FROM(
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
    FROM DWH.FACT_CLIMATE_REVIEW
    GROUP BY DATE, BUSINESS_ID
) AS R
JOIN DWH.DIM_TEMPERATURE T ON R.DATE = T.DATE
JOIN DWH.DIM_PRECIPITATION P ON R.DATE = P.DATE;



// Finding the regression on average temperature
SELECT regr_r2(AVG_STARS, (T.MIN + T.MAX)/2)
FROM(
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIWERS
    FROM DWH.FACT_CLIMATE_REVIEW
    GROUP BY DATE, BUSINESS_ID
) AS R
JOIN DWH.DIM_TEMPERATURE T ON R.DATE = T.DATE;



// Finding the regression on precipitation
SELECT regr_r2(AVG_STARS, P.precipitation)
FROM(
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIWERS
    FROM DWH.FACT_CLIMATE_REVIEW
    GROUP BY DATE, BUSINESS_ID
) AS R
JOIN DWH.DIM_PRECIPITATION P ON R.DATE = T.DATE;



// Report
SELECT B.NAME, R.MIN_TEMPERATURE, R.MAX_TEMPERATURE, R.PRECIPITATION, R.STARS
FROM DWH.FACT_CLIMATE_REVIEW R
JOIN DIM_BUSINESS B ON B.BUSINESS_ID = R.BUSINESS_ID;


